### ISSUE TITLE
sysmonitor@orcus not working on Fedora 28 beta

### ISSUE THREAD

**Issue by testman42** [linuxmint/cinnamon-spices-applets#1778]
```
 * Version 1.6.2
 * Cinnamon 3.6.7
 * Fedora 28 beta
 ```

**Notify author of applet**
@OrcusCZ 

**Issue**
Applet installed and enabled but does not appear in panel.
`libgtop2` and `libgtop2-devel` are installed.
This is what Cinnamon's debug (looking glass) says about the applet:
```
error t=2018-04-18T19:47:35Z 
[sysmonitor@orcus]: AppletDir.__init__ is undefined
[sysmonitor@orcus]: Error importing applet.js from sysmonitor@orcus
trace t=2018-04-18T19:47:35Z 
<----------------
anonymous@/home/leon/.local/share/cinnamon/applets/sysmonitor@orcus/3.2/applet.js:31:7
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:210:31
requireModule/</<@/usr/share/cinnamon/js/misc/fileUtils.js:288:25
---------------->
```

**Steps to reproduce**
- Install Fedora 28 beta
- Install Cinnamon
- Download System Monitor applet
- Enable System Monitor applet

**Expected behaviour**
System monitor graph shown in panel

**Other information**
Awesome applet, I find it very hard to live without it.

**Comment by jaszhix** [comment]
This is fixed by #1699, but I'm going to wait on merging it until @OrcusCZ approves it or Cinnamon 3.8 is released.

**Comment by nick-s-b** [comment]
After upgrading to `Cinnamon 3.8.0` and `cjs 3.8.0` , this applet stopped working. I'm getting a similar error message as above... "Error initializing applet".

**Comment by jaszhix** [comment]
@nick-s-b Did you upgrade it via applet settings? If so, can you paste the output of ~/.xsession-errors?

**Comment by nick-s-b** [comment]
@jaszhix Yep, I completely uninstalled it and reinstalled it. It's now the same as git version. However, I'm still getting the same error:

![img](https://i.imgur.com/EYPcgtd.jpg)

I have:
````
gtop 0.1.4-1
libgtop 2.38.0+13+gcab8791f-1
```` 

and .xsession-errors:
````
anonymous/MyApplet.prototype._init@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:170:24
MyApplet@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:157:5
main@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:457:20
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:573:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:347:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:94:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:246:17
---------------->
Cjs-Message: 19:06:48.362: JS LOG: [LookingGlass/info] Loaded applet tracker@glebihan in 10 ms
Cjs-Message: 19:06:48.373: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 10 ms
Cjs-Message: 19:06:48.402: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 28 ms
Cjs-Message: 19:06:48.406: JS LOG: [LookingGlass/info] Loaded applet sysmonitor@orcus in 4 ms
Cjs-Message: 19:06:48.418: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 12 ms
Cjs-Message: 19:06:48.478: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: 19:06:48.480: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 62 ms
Cjs-Message: 19:06:48.528: JS LOG: [LookingGlass/info] Loaded applet sound-with-apps-volume@koutch in 48 ms
Cjs-Message: 19:06:48.946: JS WARNING: [/usr/share/cinnamon/js/ui/popupMenu.js 1920]: reference to undefined property "_delegate"
Cjs-Message: 19:06:49.075: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 546 ms
Cjs-Message: 19:06:49.075: JS LOG: [LookingGlass/info] AppletManager started in 1168 ms
Cjs-Message: 19:06:49.077: JS LOG: [LookingGlass/info] Cinnamon took 1574 ms to start
Cjs-Message: 19:06:49.523: JS LOG: Invalid network device type, is 14
Cjs-Message: 19:06:49.523: JS LOG: network applet: Found connection for active
Cjs-Message: 19:06:49.526: JS LOG: [LookingGlass/info] Adding systray: clipit (24x24px)
Cjs-Message: 19:06:49.527: JS LOG: [LookingGlass/info] Adding systray: nvdock (24x24px)
Cjs-Message: 19:06:49.528: JS LOG: [LookingGlass/info] Adding systray: alarm-clock (24x24px)
Cjs-Message: 19:06:49.529: JS LOG: [LookingGlass/info] Hiding systray: network
Cjs-Message: 19:06:49.529: JS LOG: [LookingGlass/info] Adding systray: autokey (24x24px)
Cjs-Message: 19:06:49.531: JS LOG: [LookingGlass/info] Adding systray: blueman (24x24px)
````

There are no errors or warnings pertaining to this applet.

**Comment by nick-s-b** [comment]
@jaszhix I still can't get it working but now I'm getting a different error. I've updated both the tracker@glebihan and sysmonitor@orcus. I believe the last line, "Invalid network device type", is an error message from sysmonitor.

````
<----------------
anonymous/MyApplet.prototype._init@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:170:24
MyApplet@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:157:5
main@/home/n/.local/share/cinnamon/applets/tracker@glebihan/applet.js:457:20
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:573:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:347:22
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:290:9
---------------->
Cjs-Message: 20:37:50.899: JS LOG: [LookingGlass/info] Hiding systray: network
Cjs-Message: 20:37:50.899: JS LOG: [LookingGlass/info] Adding systray: alarm-clock (24x24px)
Cjs-Message: 20:37:50.900: JS LOG: [LookingGlass/info] Adding systray: nvdock (24x24px)
Cjs-Message: 20:37:50.900: JS LOG: [LookingGlass/info] Adding systray: blueman (24x24px)
Cjs-Message: 20:37:50.901: JS LOG: [LookingGlass/info] Adding systray: clipit (24x24px)
Cjs-Message: 20:37:50.901: JS LOG: [LookingGlass/info] Adding systray: autokey (24x24px)
Cjs-Message: 20:37:50.901: JS LOG: [LookingGlass/info] Adding systray: psensor (24x24px)
Cjs-Message: 20:37:51.176: JS LOG: Invalid network device type, is 14

````

**Comment by jaszhix** [comment]
@nick-s-b That's a non-error message from the network applet. The tracker error looks the same.

**Comment by nick-s-b** [comment]
@jake1164 I'm not sure what's wrong then. All I see is this:
![img](https://i.imgur.com/nRAJByt.jpg)
There's no error messages (other than what I posted above). Neither the tracker nor sysmon are working for me for some reason.

I'm on Arch btw... not sure if that's related.

````
cinnamon 3.8.0-1
cinnamon-control-center 3.8.0-1
cinnamon-desktop 3.8.0-1
cinnamon-menus 3.8.0-1
cinnamon-screensaver 3.8.0-1
cinnamon-session 3.8.1-1
cinnamon-settings-daemon 3.8.0-1
cinnamon-translations 3.8.0-1
libgtop 2.38.0+13+gcab8791f-1
````
Weird.

**Comment by jaszhix** [comment]
What does ~/.local/share/cinnamon/applets/sysmonitor@orcus/3.2/init.js look like? See https://github.com/linuxmint/cinnamon-spices-applets/commit/474b3e1e4d25bfde400699eb429c16c52e896220

**Comment by nick-s-b** [comment]
It appears to be identical.
````
$ cat ~/.local/share/cinnamon/applets/sysmonitor@orcus/3.2/init.js
const Gettext = imports.gettext;
const GLib = imports.gi.GLib;

var GTop;
try {
    GTop = imports.gi.GTop;
}
catch (e) {
    global.log(e)
    GTop = null;
}

const UUID = "sysmonitor@orcus";

function _(str) {
  return Gettext.dgettext(UUID, str);
}

Gettext.bindtextdomain(UUID, GLib.get_home_dir() + "/.local/share/locale")
````

**Comment by jaszhix** [comment]
The other error message you pasted for tracker was partially cut off (above the stack trace). Don't use arch, so not sure if its some other issue. Also make sure you restart Cinnamon.

**Comment by nick-s-b** [comment]
Just rebooted. Now it works. Ugh :( Apologies.

**Comment by testman42** [comment]
Still does not seem to be working for me.

Melange says
```
error t=2018-04-28T18:22:19Z 
[sysmonitor@orcus]: AppletDir.__init__ is undefined
[sysmonitor@orcus]: Error importing applet.js from sysmonitor@orcus
```

while __init__.js in the 3.2 directory looks like this:
```
const Gettext = imports.gettext;
const GLib = imports.gi.GLib;
try {
    var GTop = imports.gi.GTop;
}
catch (e) {
    var GTop = null;
}

const UUID = "sysmonitor@orcus";

function _(str) {
  return Gettext.dgettext(UUID, str);
}

Gettext.bindtextdomain(UUID, GLib.get_home_dir() + "/.local/share/locale")
```

**Comment by jaszhix** [comment]
@testman42 Yes, that's the old version, you need to upgrade.

**Comment by testman42** [comment]
Ah, ok.
I cloned from this repo and it works now.
Thank you.
