### ISSUE TITLE
Cinnamenu@json: Right-click Context Menu Doesn't Follow Cinnamon Themes Correctly

### ISSUE THREAD

**Issue by JohannPopper** [linuxmint/cinnamon-spices-applets#1923]
```
 * Latest Cinnamenu as of 8/7/18
 * Latest stable Cinnamon as of 8/7/18
 * Mint 19
 * Intel HD 4500, latest Ubuntu driver thereof
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@jaszhix

**Issue**
In all Cinnamon themes apart from Mint-Y, the right-click context menu within Cinnamenu is not properly themed/sized. In Mint-X, Linux Mint, Cinnamon default, the highlighted rectangle corners overlap the rounded corners of the menu. In practically every other Cinnamon theme in existence that I have tried (very many, Arc, Adapta, all the themes on the Spices website, etc) the right-click context menu within Cinnamenu appears unthemed, following the color scheme element, but all other themes but Mint-Y result in a very small Cinnamenu right-click context menu with blurry font that does not follow global font setting, and the menu itself is smaller than the highlight rectangle, so it appears broken and sometimes difficult to read the context menu options. Mint-Y works perfectly -- Cinnamenu's right-click context menu is themed correctly, everything readable and as expected.

**Steps to reproduce**

Install Cinnamenu. Install and apply any Cinnamon theme but Mint-Y: for example, Arc.

**Expected behaviour**

Cinnamon themes other than Mint-Y (like Arc, for example) should show the proper theme element dimensions when seeing the right-click context menu within Cinnamenu.

**Other information**

**Comment by jaszhix** [comment]
I'm confused by this one, the context menu looks fine to me using Mint-X or the Linux Mint theme. Can you provide a screenshot that highlights illegibility? You don't mention which version of Cinnamenu you are using.

![lm](https://user-images.githubusercontent.com/6859057/43815048-480e5ff0-9a93-11e8-81da-10ba439ba655.png)
![mintx](https://user-images.githubusercontent.com/6859057/43815049-4a30ba62-9a93-11e8-92a9-5c33c725e868.png)

**Comment by smurphos** [comment]
The Cinnamox themes suffer with this at the moment (in 19 and 18.3) and I haven't got round to fixing it in the themes yet.  I'm not sure which Cinnamenu update changed things because it wasn't a problem immediately after the last time I updated the themes. 

Once fixed in Cinnamox I'll port the fix into the Spice build of Adapta as-well. I'll try and do this next weekend.

**Comment by jaszhix** [comment]
The context menu is using these classes:

```js
this.menu.actor.set_style_class_name('menu menu-context-menu menu-background starkmenu-background');
```

I added those classes for the most compatibility, but if a theme is still not styled correctly I would say its a theme issue.

**Comment by smurphos** [comment]
It's fixed in Adapta and Cinnamox now anyway.
