### ISSUE TITLE
black screen on Cinnamon start even with last version of Cinnamon-spices update applet

### ISSUE THREAD

**Issue by koji54** [linuxmint/cinnamon-spices-applets#6933]
### Applet version/Build date

7.8.0

### Cinnamon version

6.4.7

### Distribution

Archlinux

### Graphics hardware *and* driver used

Amd Radeon 6800xt with amdgpu driver

### Applet name and maintainer

SpicesUpdate@claudiux @claudiux

### What happened?

[.xsession-errors_OK.txt](https://github.com/user-attachments/files/19005103/default.xsession-errors_OK.txt)
[.xsession-errors_spice_error.txt](https://github.com/user-attachments/files/19005104/default.xsession-errors_spice_error.txt)

Hi,
when this applet is installed, I've a black screen with mouse pointer only visible. After Ctrl+Alt+Esc, all is same.
I add my .xsessions-errors files.
Thanks

**Comment by claudiux** [comment]
@koji54 Thanks for reporting this issue. I'll try to fix it.

**Comment by mhjessen** [comment]
I'm experiencing the same thing.

Applet version/Build date: Version 7.8.0 (2025-02-21 10:20:48)

Cinnamon version: 6.4.8

Distribution: Linux Mint 22.1 Xia  x86_64

Graphics hardware and driver used: 

- Intel Iris Xe Graphics [Integrated]
- Display (Sceptre Z27): 3840x2160 @ 30 Hz in 27" [External]
- Display Interface: HDMI-A-1
- Display Server 1: x11 X.Org xserver-xorg-video-intel v2:2.99.917+git20210115-1build1
- Display Server 2: Xwayland v2:23.2.6-1ubuntu0.4
- Mesa: 24.2.8-1ubuntu1~24.04.1
- OpenGL: 4.6 (Compatibility Profile) Mesa 24.2.8-1ubuntu1~24.04.1
- OpenCL: 1.1 Mesa 24.2.8-1ubuntu1~24.04.1
- Vulkan: 1.3.289 - Intel open-source Mesa driver [Mesa 24.2.8-1ubuntu1~24.04.1]/

What happened?
[xsession-error-log-v2.txt](https://github.com/user-attachments/files/19014285/xsession-error-log-v2.txt)

On system startup I get a black screen with a cursor. Using Alt+F2 'r' to restart Cinnamon _sometimes_ clears up the issue but not always.  At it's worst I've had to restart the system. It's gotten better since I uninstalled the 'Weather by Gr3q', 'Lock keys indicator with notifications by Centurix', 'Timer with notifications by jake1164', and 'Restart Cinnamon by icarter09' applets, all of which were previously working fine, but I still get a black screen on every system startup.

Currently the only _workaround_ is to do multiple Alt+F2 'r' and at some point Cinnamon just starts working. 

Looking Glass was showing issues with the Weather applet not updating on startup but I don't know if that's related or not. I've attached my .xsession-errors log which shows a lot of 'Gjs-CRITICAL' errors that I don't recognize/understand.

This only started recently and was much worse at first. After removing the above applets it's gotten a _little_ better but still quite frustrating. 

Other information:

I've reinstalled all of Cinnamon, my graphics drivers, and kernel. No change.

List of Applets in use;

- GPaste Reloaded (gpaste-reloaded@feuerfuchs.eu)  Version 2.7.1 (2025-02-27 03:32:07)
- Removable drives (removable-drives@cinnamon.org)
- Enhanced Sound applet (sound150@claudiux)  Version 10.1.1 (2025-02-21 10:38:09)
- Workspace switcher (workspace-switcher@cinnamon.org)
- Settings Applet (settings@cinnamon.org)
- Spices Update (SpicesUpdate@claudiux)  Version 7.8.0 (2025-02-21 10:20:48)
- NordVPN Indicator (nordvpn-indicator@nickdurante)  
- Bluetooth
- Notifications (notifications@cinnamon.org)
- Network Manager (network@cinnamon.org)
- Calendar (calendar@cinnamon.org)
- Grouped window list (grouped-window-list@cinnamon.org)
- Panel launchers (panel-launchers@cinnamon.org)
- Menu (menu@cinnamon.org)
- XApp Status Applet (xapp-status@cinnamon.org)  Version 1.0

List of Extensions in use;

- Desktop Scroller (desktop-scroller@ccadeptic23)  Version 2.2 (2025-02-21 05:19:52)

No Desklets

**Comment by claudiux** [comment]
@mhjessen Thanks for all these details!

**Comment by daddy33** [comment]
Hello. Seems like if you don't have the package gjs installed, it works well (arch/arch based distros).

**Comment by claudiux** [comment]
@mhjessen @koji54 Do you have the `gjs` package installed?

**Comment by koji54** [comment]
No gjs installed here. I try with this package installed, but no change. Black screen is still here.

**Comment by claudiux** [comment]
Even after restarting Cinnamon?

**Comment by claudiux** [comment]
Perhaps installing `gjs` also installs dependencies that were missing.
Uninstalling `gjs` may have left these dependencies installed. One of them may be necessary for this applet to function properly when Cinnamon starts up.

**Comment by koji54** [comment]
@claudiux: yes even after a restart.
When I installed gjs to try, js128 was also installed as a dependency.

**Comment by daddy33** [comment]
I guess we can forget about gjs since I just also had the black screen without it installed (and no js128)...
Sorry.
The interesting thing is that I have two installs of my OS (ArcoLinux and regular Arch), very similar. On one of the two (the official Arch one), the black screen never occurred so far.
So I tried to investigate potential differences between both, and the only thing I found was that gjs package...

**Comment by koji54** [comment]
Well, I tried with cinnamon restored to default, but no change except one time, desktop was here but the menu bar appears partially. Date and time were visible but nothing else, no menu icon.

**Comment by mhjessen** [comment]
@claudiux: I checked **apt** and I do not have `gjs` installed there. 

I do have `cjs`, `libcjs0`, and `libcjs-dbg` v6.4.0+xia installed.

Then I checked **Flatpak** and found `gjs` installed as part of;

```
GNOME Application Platform version 46    org.gnome.Platform    46    system
GNOME Application Platform version 47    org.gnome.Platform    47    system
```

I have updated `SpicesUpdate@claudiux` to v7.8.1 and rebooted. No black screen and Looking Glass doesn't show any warnings.

The `.xsession-errors` log is another story. As you can see in the attached log I'm still flooded with `St-CRITICAL` and `Clutter-WARNING` messages.

Is it possible that there is a conflict of some kind involving `gjs` being in a sandboxed Flatpak environment while Cinnamon is locally installed?

[xsession-error-log-v3.txt](https://github.com/user-attachments/files/19044314/xsession-error-log-v3.txt)

**Comment by claudiux** [comment]
@mhjessen 

> Is it possible that there is a conflict of some kind involving gjs being in a sandboxed Flatpak environment while Cinnamon is locally installed?

That seems impossible.

**Comment by koji54** [comment]
Problem solved: after several try I delete cinnamon subfolder in .cache on my home and it works now, no more black screen with applet loaded.

**Comment by daddy33** [comment]
> Problem solved: after several try I delete cinnamon subfolder in .cache on my home and it works now, no more black screen with applet loaded.

I also did this (many times), and the issue is still there. The problem is that it occurs "on a random basis", not every time.

**Comment by claudiux** [comment]
I think I've found the source of the bug: incomplete translations in other spices (not in SpicesUpdate).

I'll do a new PR soon to take into account null messages to translate.

**Comment by daddy33** [comment]
I still got the black screen with this very last version.

**Comment by claudiux** [comment]
@mhjessen @daddy33 @koji54 Please try v7.8.4.

**Comment by daddy33** [comment]
> [@mhjessen](https://github.com/mhjessen) [@daddy33](https://github.com/daddy33) [@koji54](https://github.com/koji54) Please try v7.8.4.

I got a black screen upon restarting cinnamon.

**Comment by claudiux** [comment]
It's hard to fix a bug when you can't see it!

**Comment by claudiux** [comment]
v7.8.4 tested on LM22.1 and on Arch (EndeavourOS): no black screen, no error in `~/.xsession-errors`.

**Comment by daddy33** [comment]
Just reproduced the error on EndeavourOS, I put an ectract of the .xessiosn-errors file

```
cinnamon:34154): Gjs-CRITICAL **: 15:33:02.177: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
The offending callback was SourceFunc().
== Stack trace for context 0x64f44dac3b40 ==

(cinnamon:34154): Gjs-CRITICAL **: 15:33:02.179: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was tray-icon-added on CinnamonTrayManager 0x64f44ebd7340.
== Stack trace for context 0x64f44dac3b40 ==

(cinnamon:34154): Gjs-CRITICAL **: 15:33:02.180: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was output-added on GvcMixerControl 0x64f44fe8b800.
== Stack trace for context 0x64f44dac3b40 ==

(cinnamon:34154): Gjs-CRITICAL **: 15:33:02.180: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was output-added on GvcMixerControl 0x64f44fe8b800.
== Stack trace for context 0x64f44dac3b40 ==
```

**Comment by claudiux** [comment]
CinnamonTrayManager, GvcMixerControl...
Is SpicesUpdate installed in the same panel area as X-Tray and sound applets?
Please try moving it to another panel area.
(Next, we'll need to determine why these applets are disrupted by SpicesUpdate, or why SpicesUpdate is disrupted by these applets).

**Comment by koji54** [comment]
V 7.8.4 tested and no black screen.

below the .xsession-errors

`[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
/usr/bin/cinnamon-launcher:56: DeprecationWarning: This process (pid=3461) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.cinnamon_pid = os.fork()
Gjs-Message: 17:52:58.375: JS LOG: About to start Cinnamon (X11 backend)
Gjs-Message: 17:52:58.393: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 0 ms
Gjs-Message: 17:52:58.394: JS LOG: [LookingGlass/info] loading user theme: /home/koji/.themes/Tyr-himinn/cinnamon/cinnamon.css
Gjs-Message: 17:52:58.398: JS LOG: [LookingGlass/info] added icon directory: /home/koji/.themes/Tyr-himinn/cinnamon
Gjs-Message: 17:52:58.433: JS LOG: [LookingGlass/info] NetworkManager agent: enabled
Gjs-Message: 17:52:58.434: JS LOG: [LookingGlass/info] Polkit agent: enabled
Gjs-Message: 17:52:58.434: JS LOG: [LookingGlass/info] SSH agent: enabled
Gjs-Message: 17:52:58.435: JS LOG: [LookingGlass/info] loaded at Tue Mar 04 2025 17:52:58 GMT+0100 (heure normale d’Europe centrale)
Gjs-Message: 17:52:58.435: JS LOG: Cinnamon started at Tue Mar 04 2025 17:52:58 GMT+0100 (heure normale d’Europe centrale)
Gjs-Message: 17:52:58.438: JS LOG: [LookingGlass/info] ExtensionSystem started in 1 ms
Gjs-Message: 17:52:58.438: JS LOG: [LookingGlass/info] DeskletManager started in 1 ms
Gjs-Message: 17:52:58.438: JS LOG: [LookingGlass/info] SearchProviderManager started in 1 ms
2025/03/04 17:52:58 socat[3529] W address is opened in read-write mode but only supports read-only
Gjs-Message: 17:52:58.475: JS LOG: [LookingGlass/info] Loaded applet separator@cinnamon.org in 21 ms
Gjs-Message: 17:52:58.477: JS LOG: [LookingGlass/info] Role locked: tray
** Message: 17:52:58.477: Another instance of GeoClue DemoAgent is running.
Gjs-Message: 17:52:58.478: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 3 ms
Gjs-Message: 17:52:58.481: JS LOG: [LookingGlass/info] Loaded applet favorites@cinnamon.org in 3 ms
Gjs-Message: 17:52:58.483: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 2 ms

(cinnamon:3472): St-WARNING **: 17:52:58.490: Did not find color property 'color'
Gjs-Message: 17:52:58.495: JS LOG: [LookingGlass/info] [weather@mockturtl#34:Info]: Main Loop started.
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject

(localsearch-3:3523): Tracker-CRITICAL **: 17:52:58.501: Could not request DBus name 'org.freedesktop.LocalSearch3': D-Bus service name:'org.freedesktop.LocalSearch3' is already taken, perhaps the application is already running?
Nemo-Message: 17:52:58.505: nemo-desktop: session is cinnamon, establishing proxy
Gjs-Message: 17:52:58.526: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 43 ms
Gjs-Message: 17:52:58.528: JS LOG: [LookingGlass/info] Loaded applet windows-quick-list@cinnamon.org in 2 ms
Gjs-Message: 17:52:58.530: JS LOG: [LookingGlass/info] Loaded applet ScreenShot@tech71 in 2 ms
Gjs-Message: 17:52:58.531: JS LOG: [LookingGlass/info] Loaded applet spacer@cinnamon.org in 1 ms
Gjs-Message: 17:52:58.537: JS LOG: [LookingGlass/info] Loaded applet cornerbar@cinnamon.org in 6 ms
Gjs-Message: 17:52:58.538: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 17:52:58.540: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 3 ms
Gjs-Message: 17:52:58.548: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 8 ms
Gjs-Message: 17:52:58.551: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 3 ms
Gjs-Message: 17:52:58.553: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 2 ms
Gjs-Message: 17:52:58.554: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 17:52:58.560: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 17:52:58.560: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 7 ms
Gjs-Message: 17:52:58.569: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 9 ms
Gjs-Message: 17:52:58.570: JS LOG: [LookingGlass/info] [weather@mockturtl#34:Info]: Setting user agent to: Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0 cinnamon/6.4.8 ef3179b5773349df9a98f7dddc22bd25 
Gjs-Message: 17:52:58.575: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
Gjs-Message: 17:52:58.582: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 13 ms
Gjs-Message: 17:52:58.591: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 9 ms
Gjs-Message: 17:52:58.595: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 4 ms
Gjs-Message: 17:52:58.770: JS LOG: [LookingGlass/info] Loaded applet SpicesUpdate@claudiux in 175 ms
Gjs-Message: 17:52:58.836: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 66 ms
Gjs-Message: 17:52:58.836: JS LOG: [LookingGlass/info] AppletManager started in 400 ms
Gjs-Message: 17:52:58.837: JS LOG: [LookingGlass/info] Cinnamon took 462 ms to start
Gjs-Message: 17:52:58.841: JS LOG: Unknown network device type, is 32

(cinnamon:3472): XApp-WARNING **: 17:52:58.889: Switcheroo-control doesn't appear to be running, checking for Ubuntu support...
Gjs-Message: 17:52:58.894: JS LOG: [LookingGlass/info] GPU offload supported: false
Gjs-Message: 17:52:59.016: JS LOG: [LookingGlass/info] [weather@mockturtl#34:Info]: Weather Information refreshed

(nemo-desktop:3526): Nemo-WARNING **: 17:52:59.715: Action 'mount-archive.nemo_action' is missing dependency: gnome-disk-image-mounter
Gjs-Message: 17:53:02.765: JS LOG: Enabling WindowAttentionHandler
ATTENTION: default value of option mesa_glthread overridden by environment.
Gjs-Message: 18:07:59.276: JS LOG: [LookingGlass/info] [weather@mockturtl#34:Info]: Weather Information refreshed

`

**Comment by claudiux** [comment]
@koji54 
For 'mount-archive.nemo_action':
`apt install gnome-disk-utility`

**Comment by koji54** [comment]
thanks, 
I've seen that, but I don't mount archives and I'm on Arch so a `pacman -S gnome-disk-utility` should resolve it.

**Comment by mhjessen** [comment]
Updated to v7.8.4  OK

So far no black screen and no warnings in Looking Glass.

I've attached my .xsession-errors and it looks better than before.

[xsession-error-log-v4.txt](https://github.com/user-attachments/files/19095235/xsession-error-log-v4.txt)

**Comment by daddy33** [comment]
I still had black screens with 7.8.4. This time, I removed clutter-gtk, and since no more black screens. Wait and see, I'll keep you informed...

**Comment by daddy33** [comment]
I still have these black screens. In general, it's when I boot or reboot my system. And only on one of my systems: on the same desktop PC, I have EndeavourOS (my main system), Archlinux and Manjaro installed on 3 separate storage devices. Problem only occurring with EndeavourOS, but a few days ago, I tried to replace it with Arch (just to test), and I got the black screens...

**Comment by claudiux** [comment]
Do not place SpicesUpdate in the same panel area as the sound or systray applet.
